// Durable outbox for failed sends (the on-disk half of the failed-send UI in
// main.ts). A send that fails is written here so it survives closing the app;
// on the next open the records are read back and rebuilt as failed bubbles.
// Raw IndexedDB, no wrapper library, to keep the bundle light and deps at zero.
//
// Bytes, not Blobs: a File reference cannot be serialized across a reload, and
// WebKit on iOS has a long-standing bug reading Blobs back out of IndexedDB
// (the "Error preparing blob/file" failure), so each attachment is stored as an
// ArrayBuffer plus the name and type needed to rebuild a File on restore. Every
// read and write swallows its own errors: iOS can refuse IndexedDB entirely in
// private mode, and a lost outbox copy must never break the send flow above it.

const DB_NAME = "paratrooper";
const DB_VERSION = 1;
const STORE = "outbox";

// one stored attachment: raw image bytes plus what File() needs to wrap them
export interface OutboxFile {
  name: string;
  type: string;
  buf: ArrayBuffer;
}

// one failed send. id is stable and generated by the caller (not the DOM
// element), so a record survives across retries and reloads. ts is the send
// time, used to order restored bubbles at the tail.
export interface OutboxRecord {
  id: string;
  text: string;
  files: OutboxFile[];
  ts: number;
}

// The open is attempted once and its result (a handle, or null when IndexedDB
// is unavailable or refused) is cached for the session. A null handle turns
// every op below into a safe no-op.
let dbPromise: Promise<IDBDatabase | null> | null = null;

function openDB(): Promise<IDBDatabase | null> {
  if (dbPromise) return dbPromise;
  dbPromise = new Promise((resolve) => {
    if (typeof indexedDB === "undefined") {
      resolve(null);
      return;
    }
    let req: IDBOpenDBRequest;
    try {
      req = indexedDB.open(DB_NAME, DB_VERSION);
    } catch {
      resolve(null); // private mode can throw synchronously on open
      return;
    }
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        db.createObjectStore(STORE, { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => resolve(null);
    req.onblocked = () => resolve(null);
  });
  return dbPromise;
}

// resolves when the write transaction COMMITS (durability), not merely when the
// request succeeds; any failure resolves quietly so the caller is never thrown
function write(db: IDBDatabase, op: (store: IDBObjectStore) => void): Promise<void> {
  return new Promise((resolve) => {
    let t: IDBTransaction;
    try {
      t = db.transaction(STORE, "readwrite");
    } catch {
      resolve();
      return;
    }
    t.oncomplete = () => resolve();
    t.onerror = () => resolve();
    t.onabort = () => resolve();
    try {
      op(t.objectStore(STORE));
    } catch {
      resolve(); // e.g. a clone error preparing the bytes on iOS
    }
  });
}

function readAll(db: IDBDatabase): Promise<OutboxRecord[]> {
  return new Promise((resolve) => {
    let req: IDBRequest<OutboxRecord[]>;
    try {
      req = db.transaction(STORE, "readonly").objectStore(STORE).getAll() as IDBRequest<
        OutboxRecord[]
      >;
    } catch {
      resolve([]);
      return;
    }
    req.onsuccess = () => resolve(req.result ?? []);
    req.onerror = () => resolve([]);
  });
}

// insert or overwrite one failed-send record, keyed by its id
export async function put(record: OutboxRecord): Promise<void> {
  const db = await openDB();
  if (!db) return;
  await write(db, (store) => {
    store.put(record);
  });
}

// every stored failed send, in no particular order (the caller sorts by ts)
export async function getAll(): Promise<OutboxRecord[]> {
  const db = await openDB();
  if (!db) return [];
  return readAll(db);
}

// drop one record by id (a successful send, or Delete); a missing id is a no-op
export async function del(id: string): Promise<void> {
  const db = await openDB();
  if (!db) return;
  await write(db, (store) => {
    store.delete(id);
  });
}
